# https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github
have_fun: false  # Just review the code
memory_config:
  disabled: false
code_review:
  comment_severity_threshold: HIGH  # Reduce quantity of comments
  pull_request_opened:
    help: true  # Add a help comment to the PR
    summary: true  # Summarize the PR in a separate comment
