name: pre-commit

on:
    workflow_call:
      inputs:
        vllm:
          required: true
          type: string

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout vllm-project/vllm-ascend repo
      uses: actions/checkout@v6.0.0
    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: "3.11"
    - run: echo "::add-matcher::.github/workflows/matchers/actionlint.json"
    - run: echo "::add-matcher::.github/workflows/matchers/mypy.json"
    - name: Checkout vllm-project/vllm repo
      uses: actions/checkout@v6.0.0
      with:
        repository: vllm-project/vllm
        path: ./vllm-empty
        ref: ${{ inputs.vllm }}
    - name: Install vllm
      working-directory: vllm-empty
      run: |
        pip install -r requirements/build.txt --extra-index-url https://download.pytorch.org/whl/cpu
        VLLM_TARGET_DEVICE=empty pip install .
    - name: Install vllm-ascend dev
      run: |
        pip install -r requirements-dev.txt --extra-index-url https://download.pytorch.org/whl/cpu
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      env:
        SHELLCHECK_OPTS: "--exclude=SC2046,SC2006,SC2086" # Exclude SC2046, SC2006, SC2086 for actionlint
      with:
        extra_args: --all-files --hook-stage manual

